project:
  type: website
  output-dir: "docs"

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Eliot Mompeán"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Eliot-MA
      - icon: linkedin
        href: https://www.linkedin.com/in/eliot-mompean-asis/
      - text: Contact
        href: mailto:eliot.mompean@uah.es
format:
  html:
    theme:
      - lux
    css: styles.css

editor: visual

